### ISSUE TITLE
Tests are not building for IDEA 2022.3.3

### ISSUE THREAD

**Issue by Deirel** [HaxeFoundation/intellij-haxe#1125]
There is "cannot find symbol" Java error on the import line in the `HaxeCodeInsightFixtureTestCase` class:

```
import com.intellij.codeInsight.daemon.impl.HighlightVisitorBasedInspection
```

It appears to be that this class isn't presented in `com.jetbrains:ideaIU:2022.3.3`.

**Comment by m0rkeulv** [comment]
`DefaultHighlightVisitorBasedInspection` was removed in later versions (2023.x) and since i want to target the later version i migrated the code to use `HighlightVisitorBasedInspection` . Note that this change should not affect  the  compatibility of  built plugin  (it shuild work fine with 2022.3.3)

if you need to build with 2022.3.3 as your target for  some reason just replace 
```java
import com.intellij.codeInsight.daemon.impl.HighlightVisitorBasedInspection;
```
with
```java
import com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitorBasedInspection;
```

and
```java
  protected InspectionProfileEntry getAnnotatorBasedInspection() {
    HighlightVisitorBasedInspection inspection = new HighlightVisitorBasedInspection();
    inspection.setHighlightErrorElements(false);
    inspection.setRunAnnotators(true);
    return inspection;
  }
```
with

```java
  protected InspectionProfileEntry getAnnotatorBasedInspection() {
    return new DefaultHighlightVisitorBasedInspection.AnnotatorBasedInspection();
  }
  ```

**Comment by Deirel** [comment]
Thank you for the answer. Yes, I did just that.
Didn't know that the plugin built for 2023 should work on 2022. There is no issue in this case, I think.

**Comment by Deirel** [comment]
I'm closing the issue
